# Generated by Django 5.0.6 on 2024-05-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_package_img3_package_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
