# Generated by Django 5.0.6 on 2024-05-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_package_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
